[ubuntu]
server3  ansible_host=192.168.1.5   ansible_user=ubuntu ansible_password=123 ansible_become_password=123 


;[debian]
;server1  ansible_host=192.168.1.6   ansible_user=vm ansible_password=123 ansible_become_password=123
;server2  ansible_host=192.168.1.7   ansible_user=vm ansible_password=123 ansible_become_password=123 ansible_become_method=su

[webserver]
server3

[ubuntu:vars]
ansible_python_interpreter=/usr/bin/python3